/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UseItSoonRouteImport } from './routes/use-it-soon'
import { Route as TypeIngredientsRouteImport } from './routes/type-ingredients'
import { Route as TestChecklistRouteImport } from './routes/test-checklist'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SyncStatusRouteImport } from './routes/sync-status'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SubscriptionTermsRouteImport } from './routes/subscription-terms'
import { Route as SocialHubRouteImport } from './routes/social-hub'
import { Route as SmartKitchenRouteImport } from './routes/smart-kitchen'
import { Route as SmartInsightsRouteImport } from './routes/smart-insights'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShoppingAssistantRouteImport } from './routes/shopping-assistant'
import { Route as SeniorsRouteImport } from './routes/seniors'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SavingsHubRouteImport } from './routes/savings-hub'
import { Route as SavingsRouteImport } from './routes/savings'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as RescueRouteImport } from './routes/rescue'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as ProRouteImport } from './routes/pro'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PreserveRouteImport } from './routes/preserve'
import { Route as PremiumRecommendationsRouteImport } from './routes/premium-recommendations'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MemoryKitchenRouteImport } from './routes/memory-kitchen'
import { Route as MealPlanRouteImport } from './routes/meal-plan'
import { Route as LifeModeRouteImport } from './routes/life-mode'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as KitchenToolsRouteImport } from './routes/kitchen-tools'
import { Route as KitchenMagicRouteImport } from './routes/kitchen-magic'
import { Route as KitchenBasicsRouteImport } from './routes/kitchen-basics'
import { Route as KidsRouteImport } from './routes/kids'
import { Route as HealthCompanionRouteImport } from './routes/health-companion'
import { Route as HealthRouteImport } from './routes/health'
import { Route as GrowthRouteImport } from './routes/growth'
import { Route as GroceryPlusRouteImport } from './routes/grocery-plus'
import { Route as GoingBadRouteImport } from './routes/going-bad'
import { Route as FunModeRouteImport } from './routes/fun-mode'
import { Route as FoodPreferencesRouteImport } from './routes/food-preferences'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FastingRouteImport } from './routes/fasting'
import { Route as FamilyLegacyRouteImport } from './routes/family-legacy'
import { Route as DrinksRouteImport } from './routes/drinks'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as DayOfMealsRouteImport } from './routes/day-of-meals'
import { Route as DailyCoachRouteImport } from './routes/daily-coach'
import { Route as CupboardRouteImport } from './routes/cupboard'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ChefRescueRouteImport } from './routes/chef-rescue'
import { Route as ChefCompanionRouteImport } from './routes/chef-companion'
import { Route as BodybuilderRouteImport } from './routes/bodybuilder'
import { Route as BeforeYouShopRouteImport } from './routes/before-you-shop'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AroundTheWorldRouteImport } from './routes/around-the-world'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AboutChefRouteImport } from './routes/about-chef'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademyIndexRouteImport } from './routes/academy.index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AdminBuildSecretsRouteImport } from './routes/admin.build-secrets'
import { Route as AcademyAskRouteImport } from './routes/academy.ask'
import { Route as AcademySectionRouteImport } from './routes/academy.$section'
import { Route as ApiPublicTfDispatchRouteImport } from './routes/api/public/tf-dispatch'
import { Route as ApiAdminTriggerBuildRouteImport } from './routes/api/admin/trigger-build'
import { Route as ApiAdminPatPermissionsCheckRouteImport } from './routes/api/admin/pat-permissions-check'
import { Route as ApiAdminBuildStatusRouteImport } from './routes/api/admin/build-status'
import { Route as ApiAdminBuildSecretsStatusRouteImport } from './routes/api/admin/build-secrets-status'
import { Route as ApiAdminBuildPreflightRouteImport } from './routes/api/admin/build-preflight'
import { Route as ApiAdminBuildConfigCheckRouteImport } from './routes/api/admin/build-config-check'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const UseItSoonRoute = UseItSoonRouteImport.update({
  id: '/use-it-soon',
  path: '/use-it-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const TypeIngredientsRoute = TypeIngredientsRouteImport.update({
  id: '/type-ingredients',
  path: '/type-ingredients',
  getParentRoute: () => rootRouteImport,
} as any)
const TestChecklistRoute = TestChecklistRouteImport.update({
  id: '/test-checklist',
  path: '/test-checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncStatusRoute = SyncStatusRouteImport.update({
  id: '/sync-status',
  path: '/sync-status',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionTermsRoute = SubscriptionTermsRouteImport.update({
  id: '/subscription-terms',
  path: '/subscription-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialHubRoute = SocialHubRouteImport.update({
  id: '/social-hub',
  path: '/social-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartKitchenRoute = SmartKitchenRouteImport.update({
  id: '/smart-kitchen',
  path: '/smart-kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartInsightsRoute = SmartInsightsRouteImport.update({
  id: '/smart-insights',
  path: '/smart-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingAssistantRoute = ShoppingAssistantRouteImport.update({
  id: '/shopping-assistant',
  path: '/shopping-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const SeniorsRoute = SeniorsRouteImport.update({
  id: '/seniors',
  path: '/seniors',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsHubRoute = SavingsHubRouteImport.update({
  id: '/savings-hub',
  path: '/savings-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsRoute = SavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const RescueRoute = RescueRouteImport.update({
  id: '/rescue',
  path: '/rescue',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PreserveRoute = PreserveRouteImport.update({
  id: '/preserve',
  path: '/preserve',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRecommendationsRoute = PremiumRecommendationsRouteImport.update({
  id: '/premium-recommendations',
  path: '/premium-recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryKitchenRoute = MemoryKitchenRouteImport.update({
  id: '/memory-kitchen',
  path: '/memory-kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlanRoute = MealPlanRouteImport.update({
  id: '/meal-plan',
  path: '/meal-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeModeRoute = LifeModeRouteImport.update({
  id: '/life-mode',
  path: '/life-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenToolsRoute = KitchenToolsRouteImport.update({
  id: '/kitchen-tools',
  path: '/kitchen-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenMagicRoute = KitchenMagicRouteImport.update({
  id: '/kitchen-magic',
  path: '/kitchen-magic',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenBasicsRoute = KitchenBasicsRouteImport.update({
  id: '/kitchen-basics',
  path: '/kitchen-basics',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsRoute = KidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthCompanionRoute = HealthCompanionRouteImport.update({
  id: '/health-companion',
  path: '/health-companion',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthRoute = GrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceryPlusRoute = GroceryPlusRouteImport.update({
  id: '/grocery-plus',
  path: '/grocery-plus',
  getParentRoute: () => rootRouteImport,
} as any)
const GoingBadRoute = GoingBadRouteImport.update({
  id: '/going-bad',
  path: '/going-bad',
  getParentRoute: () => rootRouteImport,
} as any)
const FunModeRoute = FunModeRouteImport.update({
  id: '/fun-mode',
  path: '/fun-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodPreferencesRoute = FoodPreferencesRouteImport.update({
  id: '/food-preferences',
  path: '/food-preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FastingRoute = FastingRouteImport.update({
  id: '/fasting',
  path: '/fasting',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyLegacyRoute = FamilyLegacyRouteImport.update({
  id: '/family-legacy',
  path: '/family-legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinksRoute = DrinksRouteImport.update({
  id: '/drinks',
  path: '/drinks',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const DayOfMealsRoute = DayOfMealsRouteImport.update({
  id: '/day-of-meals',
  path: '/day-of-meals',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyCoachRoute = DailyCoachRouteImport.update({
  id: '/daily-coach',
  path: '/daily-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CupboardRoute = CupboardRouteImport.update({
  id: '/cupboard',
  path: '/cupboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefRescueRoute = ChefRescueRouteImport.update({
  id: '/chef-rescue',
  path: '/chef-rescue',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefCompanionRoute = ChefCompanionRouteImport.update({
  id: '/chef-companion',
  path: '/chef-companion',
  getParentRoute: () => rootRouteImport,
} as any)
const BodybuilderRoute = BodybuilderRouteImport.update({
  id: '/bodybuilder',
  path: '/bodybuilder',
  getParentRoute: () => rootRouteImport,
} as any)
const BeforeYouShopRoute = BeforeYouShopRouteImport.update({
  id: '/before-you-shop',
  path: '/before-you-shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AroundTheWorldRoute = AroundTheWorldRouteImport.update({
  id: '/around-the-world',
  path: '/around-the-world',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutChefRoute = AboutChefRouteImport.update({
  id: '/about-chef',
  path: '/about-chef',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademyRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBuildSecretsRoute = AdminBuildSecretsRouteImport.update({
  id: '/admin/build-secrets',
  path: '/admin/build-secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyAskRoute = AcademyAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademySectionRoute = AcademySectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AcademyRoute,
} as any)
const ApiPublicTfDispatchRoute = ApiPublicTfDispatchRouteImport.update({
  id: '/api/public/tf-dispatch',
  path: '/api/public/tf-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTriggerBuildRoute = ApiAdminTriggerBuildRouteImport.update({
  id: '/api/admin/trigger-build',
  path: '/api/admin/trigger-build',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPatPermissionsCheckRoute =
  ApiAdminPatPermissionsCheckRouteImport.update({
    id: '/api/admin/pat-permissions-check',
    path: '/api/admin/pat-permissions-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminBuildStatusRoute = ApiAdminBuildStatusRouteImport.update({
  id: '/api/admin/build-status',
  path: '/api/admin/build-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBuildSecretsStatusRoute =
  ApiAdminBuildSecretsStatusRouteImport.update({
    id: '/api/admin/build-secrets-status',
    path: '/api/admin/build-secrets-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminBuildPreflightRoute = ApiAdminBuildPreflightRouteImport.update({
  id: '/api/admin/build-preflight',
  path: '/api/admin/build-preflight',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBuildConfigCheckRoute =
  ApiAdminBuildConfigCheckRouteImport.update({
    id: '/api/admin/build-config-check',
    path: '/api/admin/build-config-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-chef': typeof AboutChefRoute
  '/academy': typeof AcademyRouteWithChildren
  '/account': typeof AccountRoute
  '/around-the-world': typeof AroundTheWorldRoute
  '/auth': typeof AuthRoute
  '/before-you-shop': typeof BeforeYouShopRoute
  '/bodybuilder': typeof BodybuilderRoute
  '/chef-companion': typeof ChefCompanionRoute
  '/chef-rescue': typeof ChefRescueRoute
  '/community': typeof CommunityRoute
  '/cupboard': typeof CupboardRoute
  '/daily-coach': typeof DailyCoachRoute
  '/day-of-meals': typeof DayOfMealsRoute
  '/delete-account': typeof DeleteAccountRoute
  '/drinks': typeof DrinksRoute
  '/family-legacy': typeof FamilyLegacyRoute
  '/fasting': typeof FastingRoute
  '/features': typeof FeaturesRoute
  '/food-preferences': typeof FoodPreferencesRoute
  '/fun-mode': typeof FunModeRoute
  '/going-bad': typeof GoingBadRoute
  '/grocery-plus': typeof GroceryPlusRoute
  '/growth': typeof GrowthRoute
  '/health': typeof HealthRoute
  '/health-companion': typeof HealthCompanionRoute
  '/kids': typeof KidsRoute
  '/kitchen-basics': typeof KitchenBasicsRoute
  '/kitchen-magic': typeof KitchenMagicRoute
  '/kitchen-tools': typeof KitchenToolsRoute
  '/learn': typeof LearnRoute
  '/life-mode': typeof LifeModeRoute
  '/meal-plan': typeof MealPlanRoute
  '/memory-kitchen': typeof MemoryKitchenRoute
  '/onboarding': typeof OnboardingRoute
  '/premium-recommendations': typeof PremiumRecommendationsRoute
  '/preserve': typeof PreserveRoute
  '/privacy': typeof PrivacyRoute
  '/pro': typeof ProRoute
  '/referrals': typeof ReferralsRoute
  '/reminders': typeof RemindersRoute
  '/rescue': typeof RescueRoute
  '/saved': typeof SavedRoute
  '/savings': typeof SavingsRoute
  '/savings-hub': typeof SavingsHubRoute
  '/scan': typeof ScanRoute
  '/seniors': typeof SeniorsRoute
  '/shopping-assistant': typeof ShoppingAssistantRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smart-insights': typeof SmartInsightsRoute
  '/smart-kitchen': typeof SmartKitchenRoute
  '/social-hub': typeof SocialHubRoute
  '/subscription-terms': typeof SubscriptionTermsRoute
  '/support': typeof SupportRoute
  '/sync-status': typeof SyncStatusRoute
  '/terms': typeof TermsRoute
  '/test-checklist': typeof TestChecklistRoute
  '/type-ingredients': typeof TypeIngredientsRoute
  '/use-it-soon': typeof UseItSoonRoute
  '/academy/$section': typeof AcademySectionRoute
  '/academy/ask': typeof AcademyAskRoute
  '/admin/build-secrets': typeof AdminBuildSecretsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/academy/': typeof AcademyIndexRoute
  '/api/admin/build-config-check': typeof ApiAdminBuildConfigCheckRoute
  '/api/admin/build-preflight': typeof ApiAdminBuildPreflightRoute
  '/api/admin/build-secrets-status': typeof ApiAdminBuildSecretsStatusRoute
  '/api/admin/build-status': typeof ApiAdminBuildStatusRoute
  '/api/admin/pat-permissions-check': typeof ApiAdminPatPermissionsCheckRoute
  '/api/admin/trigger-build': typeof ApiAdminTriggerBuildRoute
  '/api/public/tf-dispatch': typeof ApiPublicTfDispatchRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-chef': typeof AboutChefRoute
  '/account': typeof AccountRoute
  '/around-the-world': typeof AroundTheWorldRoute
  '/auth': typeof AuthRoute
  '/before-you-shop': typeof BeforeYouShopRoute
  '/bodybuilder': typeof BodybuilderRoute
  '/chef-companion': typeof ChefCompanionRoute
  '/chef-rescue': typeof ChefRescueRoute
  '/community': typeof CommunityRoute
  '/cupboard': typeof CupboardRoute
  '/daily-coach': typeof DailyCoachRoute
  '/day-of-meals': typeof DayOfMealsRoute
  '/delete-account': typeof DeleteAccountRoute
  '/drinks': typeof DrinksRoute
  '/family-legacy': typeof FamilyLegacyRoute
  '/fasting': typeof FastingRoute
  '/features': typeof FeaturesRoute
  '/food-preferences': typeof FoodPreferencesRoute
  '/fun-mode': typeof FunModeRoute
  '/going-bad': typeof GoingBadRoute
  '/grocery-plus': typeof GroceryPlusRoute
  '/growth': typeof GrowthRoute
  '/health': typeof HealthRoute
  '/health-companion': typeof HealthCompanionRoute
  '/kids': typeof KidsRoute
  '/kitchen-basics': typeof KitchenBasicsRoute
  '/kitchen-magic': typeof KitchenMagicRoute
  '/kitchen-tools': typeof KitchenToolsRoute
  '/learn': typeof LearnRoute
  '/life-mode': typeof LifeModeRoute
  '/meal-plan': typeof MealPlanRoute
  '/memory-kitchen': typeof MemoryKitchenRoute
  '/onboarding': typeof OnboardingRoute
  '/premium-recommendations': typeof PremiumRecommendationsRoute
  '/preserve': typeof PreserveRoute
  '/privacy': typeof PrivacyRoute
  '/pro': typeof ProRoute
  '/referrals': typeof ReferralsRoute
  '/reminders': typeof RemindersRoute
  '/rescue': typeof RescueRoute
  '/saved': typeof SavedRoute
  '/savings': typeof SavingsRoute
  '/savings-hub': typeof SavingsHubRoute
  '/scan': typeof ScanRoute
  '/seniors': typeof SeniorsRoute
  '/shopping-assistant': typeof ShoppingAssistantRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smart-insights': typeof SmartInsightsRoute
  '/smart-kitchen': typeof SmartKitchenRoute
  '/social-hub': typeof SocialHubRoute
  '/subscription-terms': typeof SubscriptionTermsRoute
  '/support': typeof SupportRoute
  '/sync-status': typeof SyncStatusRoute
  '/terms': typeof TermsRoute
  '/test-checklist': typeof TestChecklistRoute
  '/type-ingredients': typeof TypeIngredientsRoute
  '/use-it-soon': typeof UseItSoonRoute
  '/academy/$section': typeof AcademySectionRoute
  '/academy/ask': typeof AcademyAskRoute
  '/admin/build-secrets': typeof AdminBuildSecretsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/academy': typeof AcademyIndexRoute
  '/api/admin/build-config-check': typeof ApiAdminBuildConfigCheckRoute
  '/api/admin/build-preflight': typeof ApiAdminBuildPreflightRoute
  '/api/admin/build-secrets-status': typeof ApiAdminBuildSecretsStatusRoute
  '/api/admin/build-status': typeof ApiAdminBuildStatusRoute
  '/api/admin/pat-permissions-check': typeof ApiAdminPatPermissionsCheckRoute
  '/api/admin/trigger-build': typeof ApiAdminTriggerBuildRoute
  '/api/public/tf-dispatch': typeof ApiPublicTfDispatchRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-chef': typeof AboutChefRoute
  '/academy': typeof AcademyRouteWithChildren
  '/account': typeof AccountRoute
  '/around-the-world': typeof AroundTheWorldRoute
  '/auth': typeof AuthRoute
  '/before-you-shop': typeof BeforeYouShopRoute
  '/bodybuilder': typeof BodybuilderRoute
  '/chef-companion': typeof ChefCompanionRoute
  '/chef-rescue': typeof ChefRescueRoute
  '/community': typeof CommunityRoute
  '/cupboard': typeof CupboardRoute
  '/daily-coach': typeof DailyCoachRoute
  '/day-of-meals': typeof DayOfMealsRoute
  '/delete-account': typeof DeleteAccountRoute
  '/drinks': typeof DrinksRoute
  '/family-legacy': typeof FamilyLegacyRoute
  '/fasting': typeof FastingRoute
  '/features': typeof FeaturesRoute
  '/food-preferences': typeof FoodPreferencesRoute
  '/fun-mode': typeof FunModeRoute
  '/going-bad': typeof GoingBadRoute
  '/grocery-plus': typeof GroceryPlusRoute
  '/growth': typeof GrowthRoute
  '/health': typeof HealthRoute
  '/health-companion': typeof HealthCompanionRoute
  '/kids': typeof KidsRoute
  '/kitchen-basics': typeof KitchenBasicsRoute
  '/kitchen-magic': typeof KitchenMagicRoute
  '/kitchen-tools': typeof KitchenToolsRoute
  '/learn': typeof LearnRoute
  '/life-mode': typeof LifeModeRoute
  '/meal-plan': typeof MealPlanRoute
  '/memory-kitchen': typeof MemoryKitchenRoute
  '/onboarding': typeof OnboardingRoute
  '/premium-recommendations': typeof PremiumRecommendationsRoute
  '/preserve': typeof PreserveRoute
  '/privacy': typeof PrivacyRoute
  '/pro': typeof ProRoute
  '/referrals': typeof ReferralsRoute
  '/reminders': typeof RemindersRoute
  '/rescue': typeof RescueRoute
  '/saved': typeof SavedRoute
  '/savings': typeof SavingsRoute
  '/savings-hub': typeof SavingsHubRoute
  '/scan': typeof ScanRoute
  '/seniors': typeof SeniorsRoute
  '/shopping-assistant': typeof ShoppingAssistantRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smart-insights': typeof SmartInsightsRoute
  '/smart-kitchen': typeof SmartKitchenRoute
  '/social-hub': typeof SocialHubRoute
  '/subscription-terms': typeof SubscriptionTermsRoute
  '/support': typeof SupportRoute
  '/sync-status': typeof SyncStatusRoute
  '/terms': typeof TermsRoute
  '/test-checklist': typeof TestChecklistRoute
  '/type-ingredients': typeof TypeIngredientsRoute
  '/use-it-soon': typeof UseItSoonRoute
  '/academy/$section': typeof AcademySectionRoute
  '/academy/ask': typeof AcademyAskRoute
  '/admin/build-secrets': typeof AdminBuildSecretsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/academy/': typeof AcademyIndexRoute
  '/api/admin/build-config-check': typeof ApiAdminBuildConfigCheckRoute
  '/api/admin/build-preflight': typeof ApiAdminBuildPreflightRoute
  '/api/admin/build-secrets-status': typeof ApiAdminBuildSecretsStatusRoute
  '/api/admin/build-status': typeof ApiAdminBuildStatusRoute
  '/api/admin/pat-permissions-check': typeof ApiAdminPatPermissionsCheckRoute
  '/api/admin/trigger-build': typeof ApiAdminTriggerBuildRoute
  '/api/public/tf-dispatch': typeof ApiPublicTfDispatchRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-chef'
    | '/academy'
    | '/account'
    | '/around-the-world'
    | '/auth'
    | '/before-you-shop'
    | '/bodybuilder'
    | '/chef-companion'
    | '/chef-rescue'
    | '/community'
    | '/cupboard'
    | '/daily-coach'
    | '/day-of-meals'
    | '/delete-account'
    | '/drinks'
    | '/family-legacy'
    | '/fasting'
    | '/features'
    | '/food-preferences'
    | '/fun-mode'
    | '/going-bad'
    | '/grocery-plus'
    | '/growth'
    | '/health'
    | '/health-companion'
    | '/kids'
    | '/kitchen-basics'
    | '/kitchen-magic'
    | '/kitchen-tools'
    | '/learn'
    | '/life-mode'
    | '/meal-plan'
    | '/memory-kitchen'
    | '/onboarding'
    | '/premium-recommendations'
    | '/preserve'
    | '/privacy'
    | '/pro'
    | '/referrals'
    | '/reminders'
    | '/rescue'
    | '/saved'
    | '/savings'
    | '/savings-hub'
    | '/scan'
    | '/seniors'
    | '/shopping-assistant'
    | '/sitemap.xml'
    | '/smart-insights'
    | '/smart-kitchen'
    | '/social-hub'
    | '/subscription-terms'
    | '/support'
    | '/sync-status'
    | '/terms'
    | '/test-checklist'
    | '/type-ingredients'
    | '/use-it-soon'
    | '/academy/$section'
    | '/academy/ask'
    | '/admin/build-secrets'
    | '/checkout/return'
    | '/academy/'
    | '/api/admin/build-config-check'
    | '/api/admin/build-preflight'
    | '/api/admin/build-secrets-status'
    | '/api/admin/build-status'
    | '/api/admin/pat-permissions-check'
    | '/api/admin/trigger-build'
    | '/api/public/tf-dispatch'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-chef'
    | '/account'
    | '/around-the-world'
    | '/auth'
    | '/before-you-shop'
    | '/bodybuilder'
    | '/chef-companion'
    | '/chef-rescue'
    | '/community'
    | '/cupboard'
    | '/daily-coach'
    | '/day-of-meals'
    | '/delete-account'
    | '/drinks'
    | '/family-legacy'
    | '/fasting'
    | '/features'
    | '/food-preferences'
    | '/fun-mode'
    | '/going-bad'
    | '/grocery-plus'
    | '/growth'
    | '/health'
    | '/health-companion'
    | '/kids'
    | '/kitchen-basics'
    | '/kitchen-magic'
    | '/kitchen-tools'
    | '/learn'
    | '/life-mode'
    | '/meal-plan'
    | '/memory-kitchen'
    | '/onboarding'
    | '/premium-recommendations'
    | '/preserve'
    | '/privacy'
    | '/pro'
    | '/referrals'
    | '/reminders'
    | '/rescue'
    | '/saved'
    | '/savings'
    | '/savings-hub'
    | '/scan'
    | '/seniors'
    | '/shopping-assistant'
    | '/sitemap.xml'
    | '/smart-insights'
    | '/smart-kitchen'
    | '/social-hub'
    | '/subscription-terms'
    | '/support'
    | '/sync-status'
    | '/terms'
    | '/test-checklist'
    | '/type-ingredients'
    | '/use-it-soon'
    | '/academy/$section'
    | '/academy/ask'
    | '/admin/build-secrets'
    | '/checkout/return'
    | '/academy'
    | '/api/admin/build-config-check'
    | '/api/admin/build-preflight'
    | '/api/admin/build-secrets-status'
    | '/api/admin/build-status'
    | '/api/admin/pat-permissions-check'
    | '/api/admin/trigger-build'
    | '/api/public/tf-dispatch'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/about-chef'
    | '/academy'
    | '/account'
    | '/around-the-world'
    | '/auth'
    | '/before-you-shop'
    | '/bodybuilder'
    | '/chef-companion'
    | '/chef-rescue'
    | '/community'
    | '/cupboard'
    | '/daily-coach'
    | '/day-of-meals'
    | '/delete-account'
    | '/drinks'
    | '/family-legacy'
    | '/fasting'
    | '/features'
    | '/food-preferences'
    | '/fun-mode'
    | '/going-bad'
    | '/grocery-plus'
    | '/growth'
    | '/health'
    | '/health-companion'
    | '/kids'
    | '/kitchen-basics'
    | '/kitchen-magic'
    | '/kitchen-tools'
    | '/learn'
    | '/life-mode'
    | '/meal-plan'
    | '/memory-kitchen'
    | '/onboarding'
    | '/premium-recommendations'
    | '/preserve'
    | '/privacy'
    | '/pro'
    | '/referrals'
    | '/reminders'
    | '/rescue'
    | '/saved'
    | '/savings'
    | '/savings-hub'
    | '/scan'
    | '/seniors'
    | '/shopping-assistant'
    | '/sitemap.xml'
    | '/smart-insights'
    | '/smart-kitchen'
    | '/social-hub'
    | '/subscription-terms'
    | '/support'
    | '/sync-status'
    | '/terms'
    | '/test-checklist'
    | '/type-ingredients'
    | '/use-it-soon'
    | '/academy/$section'
    | '/academy/ask'
    | '/admin/build-secrets'
    | '/checkout/return'
    | '/academy/'
    | '/api/admin/build-config-check'
    | '/api/admin/build-preflight'
    | '/api/admin/build-secrets-status'
    | '/api/admin/build-status'
    | '/api/admin/pat-permissions-check'
    | '/api/admin/trigger-build'
    | '/api/public/tf-dispatch'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutChefRoute: typeof AboutChefRoute
  AcademyRoute: typeof AcademyRouteWithChildren
  AccountRoute: typeof AccountRoute
  AroundTheWorldRoute: typeof AroundTheWorldRoute
  AuthRoute: typeof AuthRoute
  BeforeYouShopRoute: typeof BeforeYouShopRoute
  BodybuilderRoute: typeof BodybuilderRoute
  ChefCompanionRoute: typeof ChefCompanionRoute
  ChefRescueRoute: typeof ChefRescueRoute
  CommunityRoute: typeof CommunityRoute
  CupboardRoute: typeof CupboardRoute
  DailyCoachRoute: typeof DailyCoachRoute
  DayOfMealsRoute: typeof DayOfMealsRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  DrinksRoute: typeof DrinksRoute
  FamilyLegacyRoute: typeof FamilyLegacyRoute
  FastingRoute: typeof FastingRoute
  FeaturesRoute: typeof FeaturesRoute
  FoodPreferencesRoute: typeof FoodPreferencesRoute
  FunModeRoute: typeof FunModeRoute
  GoingBadRoute: typeof GoingBadRoute
  GroceryPlusRoute: typeof GroceryPlusRoute
  GrowthRoute: typeof GrowthRoute
  HealthRoute: typeof HealthRoute
  HealthCompanionRoute: typeof HealthCompanionRoute
  KidsRoute: typeof KidsRoute
  KitchenBasicsRoute: typeof KitchenBasicsRoute
  KitchenMagicRoute: typeof KitchenMagicRoute
  KitchenToolsRoute: typeof KitchenToolsRoute
  LearnRoute: typeof LearnRoute
  LifeModeRoute: typeof LifeModeRoute
  MealPlanRoute: typeof MealPlanRoute
  MemoryKitchenRoute: typeof MemoryKitchenRoute
  OnboardingRoute: typeof OnboardingRoute
  PremiumRecommendationsRoute: typeof PremiumRecommendationsRoute
  PreserveRoute: typeof PreserveRoute
  PrivacyRoute: typeof PrivacyRoute
  ProRoute: typeof ProRoute
  ReferralsRoute: typeof ReferralsRoute
  RemindersRoute: typeof RemindersRoute
  RescueRoute: typeof RescueRoute
  SavedRoute: typeof SavedRoute
  SavingsRoute: typeof SavingsRoute
  SavingsHubRoute: typeof SavingsHubRoute
  ScanRoute: typeof ScanRoute
  SeniorsRoute: typeof SeniorsRoute
  ShoppingAssistantRoute: typeof ShoppingAssistantRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SmartInsightsRoute: typeof SmartInsightsRoute
  SmartKitchenRoute: typeof SmartKitchenRoute
  SocialHubRoute: typeof SocialHubRoute
  SubscriptionTermsRoute: typeof SubscriptionTermsRoute
  SupportRoute: typeof SupportRoute
  SyncStatusRoute: typeof SyncStatusRoute
  TermsRoute: typeof TermsRoute
  TestChecklistRoute: typeof TestChecklistRoute
  TypeIngredientsRoute: typeof TypeIngredientsRoute
  UseItSoonRoute: typeof UseItSoonRoute
  AdminBuildSecretsRoute: typeof AdminBuildSecretsRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiAdminBuildConfigCheckRoute: typeof ApiAdminBuildConfigCheckRoute
  ApiAdminBuildPreflightRoute: typeof ApiAdminBuildPreflightRoute
  ApiAdminBuildSecretsStatusRoute: typeof ApiAdminBuildSecretsStatusRoute
  ApiAdminBuildStatusRoute: typeof ApiAdminBuildStatusRoute
  ApiAdminPatPermissionsCheckRoute: typeof ApiAdminPatPermissionsCheckRoute
  ApiAdminTriggerBuildRoute: typeof ApiAdminTriggerBuildRoute
  ApiPublicTfDispatchRoute: typeof ApiPublicTfDispatchRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/use-it-soon': {
      id: '/use-it-soon'
      path: '/use-it-soon'
      fullPath: '/use-it-soon'
      preLoaderRoute: typeof UseItSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/type-ingredients': {
      id: '/type-ingredients'
      path: '/type-ingredients'
      fullPath: '/type-ingredients'
      preLoaderRoute: typeof TypeIngredientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-checklist': {
      id: '/test-checklist'
      path: '/test-checklist'
      fullPath: '/test-checklist'
      preLoaderRoute: typeof TestChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync-status': {
      id: '/sync-status'
      path: '/sync-status'
      fullPath: '/sync-status'
      preLoaderRoute: typeof SyncStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription-terms': {
      id: '/subscription-terms'
      path: '/subscription-terms'
      fullPath: '/subscription-terms'
      preLoaderRoute: typeof SubscriptionTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-hub': {
      id: '/social-hub'
      path: '/social-hub'
      fullPath: '/social-hub'
      preLoaderRoute: typeof SocialHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-kitchen': {
      id: '/smart-kitchen'
      path: '/smart-kitchen'
      fullPath: '/smart-kitchen'
      preLoaderRoute: typeof SmartKitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-insights': {
      id: '/smart-insights'
      path: '/smart-insights'
      fullPath: '/smart-insights'
      preLoaderRoute: typeof SmartInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping-assistant': {
      id: '/shopping-assistant'
      path: '/shopping-assistant'
      fullPath: '/shopping-assistant'
      preLoaderRoute: typeof ShoppingAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seniors': {
      id: '/seniors'
      path: '/seniors'
      fullPath: '/seniors'
      preLoaderRoute: typeof SeniorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings-hub': {
      id: '/savings-hub'
      path: '/savings-hub'
      fullPath: '/savings-hub'
      preLoaderRoute: typeof SavingsHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings': {
      id: '/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rescue': {
      id: '/rescue'
      path: '/rescue'
      fullPath: '/rescue'
      preLoaderRoute: typeof RescueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preserve': {
      id: '/preserve'
      path: '/preserve'
      fullPath: '/preserve'
      preLoaderRoute: typeof PreserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium-recommendations': {
      id: '/premium-recommendations'
      path: '/premium-recommendations'
      fullPath: '/premium-recommendations'
      preLoaderRoute: typeof PremiumRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory-kitchen': {
      id: '/memory-kitchen'
      path: '/memory-kitchen'
      fullPath: '/memory-kitchen'
      preLoaderRoute: typeof MemoryKitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-plan': {
      id: '/meal-plan'
      path: '/meal-plan'
      fullPath: '/meal-plan'
      preLoaderRoute: typeof MealPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life-mode': {
      id: '/life-mode'
      path: '/life-mode'
      fullPath: '/life-mode'
      preLoaderRoute: typeof LifeModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-tools': {
      id: '/kitchen-tools'
      path: '/kitchen-tools'
      fullPath: '/kitchen-tools'
      preLoaderRoute: typeof KitchenToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-magic': {
      id: '/kitchen-magic'
      path: '/kitchen-magic'
      fullPath: '/kitchen-magic'
      preLoaderRoute: typeof KitchenMagicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-basics': {
      id: '/kitchen-basics'
      path: '/kitchen-basics'
      fullPath: '/kitchen-basics'
      preLoaderRoute: typeof KitchenBasicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids': {
      id: '/kids'
      path: '/kids'
      fullPath: '/kids'
      preLoaderRoute: typeof KidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-companion': {
      id: '/health-companion'
      path: '/health-companion'
      fullPath: '/health-companion'
      preLoaderRoute: typeof HealthCompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth': {
      id: '/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof GrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grocery-plus': {
      id: '/grocery-plus'
      path: '/grocery-plus'
      fullPath: '/grocery-plus'
      preLoaderRoute: typeof GroceryPlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/going-bad': {
      id: '/going-bad'
      path: '/going-bad'
      fullPath: '/going-bad'
      preLoaderRoute: typeof GoingBadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fun-mode': {
      id: '/fun-mode'
      path: '/fun-mode'
      fullPath: '/fun-mode'
      preLoaderRoute: typeof FunModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-preferences': {
      id: '/food-preferences'
      path: '/food-preferences'
      fullPath: '/food-preferences'
      preLoaderRoute: typeof FoodPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fasting': {
      id: '/fasting'
      path: '/fasting'
      fullPath: '/fasting'
      preLoaderRoute: typeof FastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-legacy': {
      id: '/family-legacy'
      path: '/family-legacy'
      fullPath: '/family-legacy'
      preLoaderRoute: typeof FamilyLegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinks': {
      id: '/drinks'
      path: '/drinks'
      fullPath: '/drinks'
      preLoaderRoute: typeof DrinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day-of-meals': {
      id: '/day-of-meals'
      path: '/day-of-meals'
      fullPath: '/day-of-meals'
      preLoaderRoute: typeof DayOfMealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-coach': {
      id: '/daily-coach'
      path: '/daily-coach'
      fullPath: '/daily-coach'
      preLoaderRoute: typeof DailyCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cupboard': {
      id: '/cupboard'
      path: '/cupboard'
      fullPath: '/cupboard'
      preLoaderRoute: typeof CupboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef-rescue': {
      id: '/chef-rescue'
      path: '/chef-rescue'
      fullPath: '/chef-rescue'
      preLoaderRoute: typeof ChefRescueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef-companion': {
      id: '/chef-companion'
      path: '/chef-companion'
      fullPath: '/chef-companion'
      preLoaderRoute: typeof ChefCompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bodybuilder': {
      id: '/bodybuilder'
      path: '/bodybuilder'
      fullPath: '/bodybuilder'
      preLoaderRoute: typeof BodybuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/before-you-shop': {
      id: '/before-you-shop'
      path: '/before-you-shop'
      fullPath: '/before-you-shop'
      preLoaderRoute: typeof BeforeYouShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/around-the-world': {
      id: '/around-the-world'
      path: '/around-the-world'
      fullPath: '/around-the-world'
      preLoaderRoute: typeof AroundTheWorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-chef': {
      id: '/about-chef'
      path: '/about-chef'
      fullPath: '/about-chef'
      preLoaderRoute: typeof AboutChefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/': {
      id: '/academy/'
      path: '/'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/build-secrets': {
      id: '/admin/build-secrets'
      path: '/admin/build-secrets'
      fullPath: '/admin/build-secrets'
      preLoaderRoute: typeof AdminBuildSecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/ask': {
      id: '/academy/ask'
      path: '/ask'
      fullPath: '/academy/ask'
      preLoaderRoute: typeof AcademyAskRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/$section': {
      id: '/academy/$section'
      path: '/$section'
      fullPath: '/academy/$section'
      preLoaderRoute: typeof AcademySectionRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/api/public/tf-dispatch': {
      id: '/api/public/tf-dispatch'
      path: '/api/public/tf-dispatch'
      fullPath: '/api/public/tf-dispatch'
      preLoaderRoute: typeof ApiPublicTfDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/trigger-build': {
      id: '/api/admin/trigger-build'
      path: '/api/admin/trigger-build'
      fullPath: '/api/admin/trigger-build'
      preLoaderRoute: typeof ApiAdminTriggerBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/pat-permissions-check': {
      id: '/api/admin/pat-permissions-check'
      path: '/api/admin/pat-permissions-check'
      fullPath: '/api/admin/pat-permissions-check'
      preLoaderRoute: typeof ApiAdminPatPermissionsCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/build-status': {
      id: '/api/admin/build-status'
      path: '/api/admin/build-status'
      fullPath: '/api/admin/build-status'
      preLoaderRoute: typeof ApiAdminBuildStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/build-secrets-status': {
      id: '/api/admin/build-secrets-status'
      path: '/api/admin/build-secrets-status'
      fullPath: '/api/admin/build-secrets-status'
      preLoaderRoute: typeof ApiAdminBuildSecretsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/build-preflight': {
      id: '/api/admin/build-preflight'
      path: '/api/admin/build-preflight'
      fullPath: '/api/admin/build-preflight'
      preLoaderRoute: typeof ApiAdminBuildPreflightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/build-config-check': {
      id: '/api/admin/build-config-check'
      path: '/api/admin/build-config-check'
      fullPath: '/api/admin/build-config-check'
      preLoaderRoute: typeof ApiAdminBuildConfigCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AcademyRouteChildren {
  AcademySectionRoute: typeof AcademySectionRoute
  AcademyAskRoute: typeof AcademyAskRoute
  AcademyIndexRoute: typeof AcademyIndexRoute
}

const AcademyRouteChildren: AcademyRouteChildren = {
  AcademySectionRoute: AcademySectionRoute,
  AcademyAskRoute: AcademyAskRoute,
  AcademyIndexRoute: AcademyIndexRoute,
}

const AcademyRouteWithChildren =
  AcademyRoute._addFileChildren(AcademyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutChefRoute: AboutChefRoute,
  AcademyRoute: AcademyRouteWithChildren,
  AccountRoute: AccountRoute,
  AroundTheWorldRoute: AroundTheWorldRoute,
  AuthRoute: AuthRoute,
  BeforeYouShopRoute: BeforeYouShopRoute,
  BodybuilderRoute: BodybuilderRoute,
  ChefCompanionRoute: ChefCompanionRoute,
  ChefRescueRoute: ChefRescueRoute,
  CommunityRoute: CommunityRoute,
  CupboardRoute: CupboardRoute,
  DailyCoachRoute: DailyCoachRoute,
  DayOfMealsRoute: DayOfMealsRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  DrinksRoute: DrinksRoute,
  FamilyLegacyRoute: FamilyLegacyRoute,
  FastingRoute: FastingRoute,
  FeaturesRoute: FeaturesRoute,
  FoodPreferencesRoute: FoodPreferencesRoute,
  FunModeRoute: FunModeRoute,
  GoingBadRoute: GoingBadRoute,
  GroceryPlusRoute: GroceryPlusRoute,
  GrowthRoute: GrowthRoute,
  HealthRoute: HealthRoute,
  HealthCompanionRoute: HealthCompanionRoute,
  KidsRoute: KidsRoute,
  KitchenBasicsRoute: KitchenBasicsRoute,
  KitchenMagicRoute: KitchenMagicRoute,
  KitchenToolsRoute: KitchenToolsRoute,
  LearnRoute: LearnRoute,
  LifeModeRoute: LifeModeRoute,
  MealPlanRoute: MealPlanRoute,
  MemoryKitchenRoute: MemoryKitchenRoute,
  OnboardingRoute: OnboardingRoute,
  PremiumRecommendationsRoute: PremiumRecommendationsRoute,
  PreserveRoute: PreserveRoute,
  PrivacyRoute: PrivacyRoute,
  ProRoute: ProRoute,
  ReferralsRoute: ReferralsRoute,
  RemindersRoute: RemindersRoute,
  RescueRoute: RescueRoute,
  SavedRoute: SavedRoute,
  SavingsRoute: SavingsRoute,
  SavingsHubRoute: SavingsHubRoute,
  ScanRoute: ScanRoute,
  SeniorsRoute: SeniorsRoute,
  ShoppingAssistantRoute: ShoppingAssistantRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SmartInsightsRoute: SmartInsightsRoute,
  SmartKitchenRoute: SmartKitchenRoute,
  SocialHubRoute: SocialHubRoute,
  SubscriptionTermsRoute: SubscriptionTermsRoute,
  SupportRoute: SupportRoute,
  SyncStatusRoute: SyncStatusRoute,
  TermsRoute: TermsRoute,
  TestChecklistRoute: TestChecklistRoute,
  TypeIngredientsRoute: TypeIngredientsRoute,
  UseItSoonRoute: UseItSoonRoute,
  AdminBuildSecretsRoute: AdminBuildSecretsRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiAdminBuildConfigCheckRoute: ApiAdminBuildConfigCheckRoute,
  ApiAdminBuildPreflightRoute: ApiAdminBuildPreflightRoute,
  ApiAdminBuildSecretsStatusRoute: ApiAdminBuildSecretsStatusRoute,
  ApiAdminBuildStatusRoute: ApiAdminBuildStatusRoute,
  ApiAdminPatPermissionsCheckRoute: ApiAdminPatPermissionsCheckRoute,
  ApiAdminTriggerBuildRoute: ApiAdminTriggerBuildRoute,
  ApiPublicTfDispatchRoute: ApiPublicTfDispatchRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
